name: Update customized from master

on:
  workflow_dispatch:

  push:
    branches:
      - master

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with: 
          ref: 'customized'
      - name: Rebase branch on master
        run: |
          git fetch --unshallow
          git config --local user.name "${GITHUB_ACTOR}"
          git config --local user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git rebase origin/master
          git push --force-with-lease origin customized
